# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Set-Timezone
version:      0.05
version_from: lib/Date/Set/Timezone.pm
installdirs:  site
requires:
    Date::ICal:                    1.70
    Date::Set:                     1.26
    Set::Infinite:                 0.43
    Test::Harness:                 1.23
    Test::More:                    0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
